package bitlap.sbt.analyzer.util

import java.nio.file.Path

import bitlap.sbt.analyzer.*
import bitlap.sbt.analyzer.activity.WhatsNew
import bitlap.sbt.analyzer.activity.WhatsNew.canBrowseInHTMLEditor

import org.jetbrains.plugins.scala.*
import org.jetbrains.plugins.scala.project.Version
import org.jetbrains.sbt.project.SbtProjectSystem

import com.intellij.icons.AllIcons
import com.intellij.ide.BrowserUtil
import com.intellij.notification.*
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.externalSystem.autoimport.ProjectRefreshAction
import com.intellij.openapi.externalSystem.importing.ImportSpecBuilder
import com.intellij.openapi.externalSystem.util.ExternalSystemUtil
import com.intellij.openapi.fileEditor.*
import com.intellij.openapi.project.{ DumbAwareAction, Project }
import com.intellij.openapi.vfs.VfsUtil

/** SbtDependencyAnalyzer global notifier
 */
object Notifications {

  private lazy val NotificationGroup =
    NotificationGroupManager.getInstance().getNotificationGroup("Sbt.DependencyAnalyzer.Notification")

  private def getTextForAnalyzer(project: Project): String = {
    val sbtVersion = Version(SbtUtils.getSbtVersion(project))
    val line = if (sbtVersion.major(2) >= Version("1.4")) {
      "addDependencyTreePlugin"
    } else {
      if (sbtVersion.major(3) >= Version("0.13.10")) {
        "addSbtPlugin(\"net.virtual-void\" % \"sbt-dependency-graph\" % \"0.9.2\")"
      } else {
        "addSbtPlugin(\"net.virtual-void\" % \"sbt-dependency-graph\" % \"0.8.2\")"
      }
    }
    "// -- This file was mechanically generated by Sbt Dependency Plugin: Do not edit! -- //" + Constants.Line_Separator + line
  }

  def notifyParseFileError(file: String): Unit = {
    // add notification when gets vfsFile timeout
    val notification = NotificationGroup
      .createNotification(
        SbtDependencyAnalyzerBundle.message("analyzer.task.error.title"),
        SbtDependencyAnalyzerBundle.message("analyzer.task.error.text", file),
        NotificationType.ERROR
      )
      .setIcon(SbtDependencyAnalyzerIcons.ICON)
    notification.notify(null)
  }

  def notifyUnknownError(project: Project, command: String, moduleId: String, scope: DependencyScopeEnum): Unit = {
    // add notification
    val notification = NotificationGroup
      .createNotification(
        SbtDependencyAnalyzerBundle.message("analyzer.task.error.title"),
        SbtDependencyAnalyzerBundle.message("analyzer.task.error.unknown.text", moduleId, scope.toString, command),
        NotificationType.ERROR
      )
      .setIcon(SbtDependencyAnalyzerIcons.ICON)
    notification.notify(project)
  }

  def notifyAndAddDependencyTreePlugin(project: Project): Unit = {
    // get project/plugins.sbt
    // val pluginSbtFileName = "plugins.sbt"
    val pluginSbtFileName = "sdap.sbt"
    val basePath          = VfsUtil.findFile(Path.of(project.getBasePath), true)

    WriteCommandAction.runWriteCommandAction(
      project,
      new Runnable() {
        override def run(): Unit = {
          // 1. get or create sdap.sbt file and add dependency tree statement
          val projectPath    = VfsUtil.createDirectoryIfMissing(basePath, "project")
          val pluginsSbtFile = projectPath.findOrCreateChildData(null, pluginSbtFileName)
          val doc            = FileDocumentManager.getInstance().getDocument(pluginsSbtFile)
          doc.setReadOnly(false)
          doc.setText(doc.getText + Constants.Line_Separator + getTextForAnalyzer(project))
          // if Intellij not enable auto-reload
          // ProjectRefreshAction.Companion.refreshProject(project)
          // force refresh project
          ExternalSystemUtil.refreshProjects(new ImportSpecBuilder(project, SbtProjectSystem.Id))
          waitInterval(2000)

          // 2. add notification
          val addNotification = NotificationGroup
            .createNotification(
              SbtDependencyAnalyzerBundle.message("analyzer.notification.add.sdap.plugin.title"),
              SbtDependencyAnalyzerBundle.message("analyzer.notification.add.sdap.plugin.text", pluginSbtFileName),
              NotificationType.INFORMATION
            )
            .setIcon(SbtDependencyAnalyzerIcons.ICON)
            .addAction(
              new NotificationAction(
                SbtDependencyAnalyzerBundle.message("analyzer.notification.gotoPluginsFile", pluginSbtFileName)
              ) {
                override def actionPerformed(e: AnActionEvent, notification: Notification): Unit = {
                  WriteCommandAction.runWriteCommandAction(
                    project,
                    new Runnable() {
                      override def run(): Unit = {
                        notification.expire()
                        val recheckFile = VfsUtil.findRelativeFile(basePath, "project", pluginSbtFileName)
                        if (recheckFile != null) {
                          FileEditorManager
                            .getInstance(project)
                            .openTextEditor(new OpenFileDescriptor(project, recheckFile), true)
                        }
                      }
                    }
                  )
                }
              }
            )
          addNotification.notify(project)
        }
      }
    )
  }

  /** notify infomation when update plugin
   */
  def notifyUpdateActivity(project: Project, version: Version, title: String, content: String): Unit = {
    val notification = NotificationGroup
      .createNotification(content, NotificationType.INFORMATION)
      .setTitle(title)
      .setImportant(true)
      .setIcon(SbtDependencyAnalyzerIcons.ICON)
      .setListenerIfSupport(NotificationListener.URL_OPENING_LISTENER)
    if (canBrowseInHTMLEditor) {
      notification.whenExpired(() => WhatsNew.browse(version, project))
      waitInterval(10000)
      notification.expire()
    } else {
      notification.addAction(
        new DumbAwareAction(
          SbtDependencyAnalyzerBundle.message("analyzer.updated.notification.gotoBrowser"),
          null,
          AllIcons.General.Web
        ) {
          override def actionPerformed(e: AnActionEvent): Unit = BrowserUtil.browse(WhatsNew.getReleaseNotes(version))
        }
      )
    }
    notification.notify(project)
  }

  extension (notification: Notification) {

    private def setListenerIfSupport(listener: NotificationListener): Notification = {
      try {
        org.joor.Reflect.on(notification).call("setListener", listener)
      } catch {
        case _: Throwable =>
        // ignore
      }
      notification
    }
  }
}
