package bitlap.sbt.analyzer.parser

/** @param cmd
 *    The sbt task to generate file to be analyzed
 *  @param suffix
 *    The suffix of the file generated by the [[cmd]] task
 */
enum AnalyzedFileType(val cmd: String, val suffix: String) {
  case Dot     extends AnalyzedFileType("dependencyDot", "dot")
  case GraphML extends AnalyzedFileType("dependencyGraphML", "graphml")
}
