package bitlap.sbt.analyzer.parsing

/** To handle the analysis of files generated by specific sbt tasks, where the task name and output file suffix are
 *  provided as parameters.
 *
 *  @param cmd
 *    The sbt task responsible for generating the file that requires analysis.
 *  @param suffix
 *    The file extension (e.g., .dot) of the output file produced by the cmd task, used to identify and process the
 *    correct file.
 */
enum DependencyGraphType(val cmd: String, val suffix: String) {
  case Dot     extends DependencyGraphType("dependencyDot", "dot")
  case GraphML extends DependencyGraphType("dependencyGraphML", "graphml")
}
